{% set name = "diptox" %}
{% set version = "1.0.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a216e10c31d45200a26d9d6f09ab2c710d3bfde0836325ec9eca73128251713f

build:
  entry_points:
    - diptox-gui = diptox.cli:run_gui
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - pandas
    - rdkit >=2023.3
    - tqdm
    - scipy
    - openpyxl
    - streamlit >=1.0.0

test:
  imports:
    - diptox
  commands:
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/diptox/
  summary: Data Integration and Processing for Computational Toxicology
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hya0FAD
